- type: replace
  path: /releases/name=syslog-migration?
  value:
    name: syslog-migration
    version: 8 # changed by the pipeline
    url: https://github.com/pivotal-cf/syslog-migration-release/releases/download/v8/syslog-migration-8.tgz
    sha1: 59f49b55b36223f458a8c437b0931d511ad748a7

- type: replace
  path: /instance_groups/name=rmq-broker/jobs/-
  value:
    name: syslog_forwarder
    release: syslog-migration
    properties:
      syslog:
        forward_files: false
        migration:
          message_format: rfc5424
        address: ((syslog-host))
        port: ((syslog-port))
        transport: tcp
        custom_rule: |
          module(load="imfile")

          input(type="imfile"
                File="/var/vcap/sys/log/rabbitmq-broker/startup_stdout.log"
                Tag="rabbitmq_broker_startup_stdout")

          input(type="imfile"
                File="/var/vcap/sys/log/rabbitmq-broker/startup_stderr.log"
                Tag="rabbitmq_broker_startup_stderr")

          input(type="imfile"
                File="/var/vcap/sys/log/route_registrar/route_registrar.log"
                Tag="rabbitmq_broker_route_registrar_stdout")

          input(type="imfile"
                File="/var/vcap/sys/log/route_registrar/route_registrar.err.log"
                Tag="rabbitmq_broker_route_registrar_stderr")

