---
- type: replace
  path: /releases/name=go-syslog?
  value:
    name: go-syslogd
    version: latest

- type: replace
  path: /instance_groups/-
  value:
    name: syslog-test-endpoint
    instances: 1
    jobs:
      - name: go-syslogd
        release: go-syslogd
        properties:
          go_syslogd:
            syslogd:
              format: legacy
              port: ((syslog-port))
            http:
              port: 8080
    azs:
    - eu-west-1a
    instances: 1
    networks:
    - name: services
      static_ips:
      - ((syslog-host))
    stemcell: trusty
    vm_type: m3.medium
