---
- type: replace
  path: /releases/name=cf-rabbitmq?
  value:
    name: cf-rabbitmq
    version: 232.0.0
    url: https://bosh.io/d/github.com/pivotal-cf/cf-rabbitmq-release?v=232.0.0
    sha1: 7225d4a5beeca634ddc85c661eb804172982f73c

- type: replace
  path: /instance_groups/-
  value:
    name: rmq
    instances: 3
    jobs:
    - name: rabbitmq-server
      release: cf-rabbitmq
      properties:
        rabbitmq-server:
          restart_statsdb_cron_schedule: "42 */4 * * *"
          plugins:
          - rabbitmq_management
          - rabbitmq_mqtt
          - rabbitmq_stomp
          ports:
          - 5672
          - 5671
          - 1883
          - 8883
          - 61613
          - 61614
          - 15672
          - 15674
          administrators:
            management:
              username: ((rabbitmq-management-username))
              password: ((rabbitmq-management-password))
            broker:
              username: ((rabbitmq-broker-username))
              password: ((rabbitmq-broker-password))
          cookie: "rabbit-cluster:aws"
          cluster_partition_handling: ((cluster-partition-handling-strategy))
    vm_type: n1-highmem-4
    stemcell: trusty
    persistent_disk_type: 100GB
    networks:
    - name: default
    azs:
    - z1
    - z2

- type: replace
  path: /instance_groups/-
  value:
    name: haproxy
    instances: ((haproxy-instances))
    jobs:
    - name: rabbitmq-haproxy
      release: cf-rabbitmq
      properties:
        rabbitmq-haproxy:
          stats:
            username: ((haproxy-stats-username))
            password: ((haproxy-stats-password))
    - name: route_registrar
      release: routing
      consumes:
        nats: {from: nats, deployment: cf}
      properties:
        route_registrar:
          routes:
          - name: ((rabbitmq-management-domain))
            port: 15672
            registration_interval: 20s
            uris:
            - ((rabbitmq-management-domain)).((bosh-domain))
    vm_type: n1-standard-1
    stemcell: trusty
    networks:
    - name: default
    azs:
    - z1
    - z2
