---
director_uuid: 300ee127-aeb7-4691-98ff-7fb38a658b3a
instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: rabbitmq-broker
    release: cf-rabbitmq-broker
  - name: route_registrar
    properties:
      nats:
        machines:
        - 10.0.31.191
        - 10.0.47.191
        password: 63r20kzm397fdyotdux7
        port: 4222
        user: nats
      route_registrar:
        routes:
        - name: pivotal-rabbitmq-broker
          port: 4567
          registration_interval: 20s
          uris:
          - pivotal-rabbitmq-broker.jeunet.cf-rabbitmq.gcp.london.cf-app.com
    release: routing
  - name: syslog-configuration-test
    properties:
      syslog-configuration-test:
        watched-log-files:
        - "/var/vcap/sys/log/rabbitmq-broker/startup_stdout.log"
        - "/var/vcap/sys/log/rabbitmq-broker/startup_stderr.log"
        - "/var/vcap/sys/log/route_registrar/route_registrar.log"
        - "/var/vcap/sys/log/route_registrar/route_registrar.err.log"
    release: cf-rabbitmq-test
  - name: permissions-test
    properties:
      permissions-test:
        directories:
        - "/var/vcap/jobs/rabbitmq-broker"
        - "/var/vcap/sys/log"
    release: cf-rabbitmq-test
  name: rmq-broker
  networks:
  - name: default
  stemcell: trusty
  vm_type: m3.medium
- azs:
  - z1
  instances: 1
  jobs:
  - name: broker-registrar
    release: cf-rabbitmq-broker
  lifecycle: errand
  name: broker-registrar
  networks:
  - name: default
  stemcell: trusty
  vm_type: t2.small
- azs:
  - z1
  instances: 1
  jobs:
  - name: broker-deregistrar
    release: cf-rabbitmq-broker
  lifecycle: errand
  name: broker-deregistrar
  networks:
  - name: default
  stemcell: trusty
  vm_type: t2.small
- azs:
  - z1
  instances: 1
  jobs:
  - name: smoke-tests
    release: cf-rabbitmq-broker
  lifecycle: errand
  name: smoke-tests
  networks:
  - name: default
  stemcell: trusty
  vm_type: m3.medium
name: cf-rabbitmq-broker
properties:
  broker:
    host: pivotal-rabbitmq-broker.jeunet.cf-rabbitmq.gcp.london.cf-app.com
    name: p-rabbitmq-without-badgers
    password: disappointing30guineapigs
    protocol: http
    service:
      name: p-rabbitmq-without-badgers
    username: multitenant-rabbitmq-broker
  cf:
    admin_password: 109kmi03n48l9ba4zzdm
    admin_username: admin
    api_url: http://api.jeunet.cf-rabbitmq.gcp.london.cf-app.com
    domain: jeunet.cf-rabbitmq.gcp.london.cf-app.com
  rabbitmq-broker:
    cc_endpoint: http://api.jeunet.cf-rabbitmq.gcp.london.cf-app.com
    logging:
      level: debug
      print_stack_traces: false
    rabbitmq:
      administrator:
        password: thealbatrossfliesbackwards
        username: rabbitmq-broker
      hosts:
      - 10.0.32.17
      - 10.0.16.21
      management_domain: pivotal-rabbitmq-broker.jeunet.cf-rabbitmq.gcp.london.cf-app.com
      operator_set_policy:
        enabled: true
        policy_definition: '{"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"}'
        policy_name: operator_set_policy
        policy_priority: 50
      ssl: true
    route: pivotal-rabbitmq-broker
    service:
      name: p-rabbitmq-without-badgers
      password: disappointing30guineapigs
      plan_uuid: 1957C8D1-D10A-48D1-8682-36D2855CF974
      username: multitenant-rabbitmq-broker
      uuid: 13BBF783-6423-4B04-8A2E-7CFB2C820DF8
    syslog_aggregator:
      address: logs5.papertrailapp.com
      port: 14522
releases:
- name: cf-rabbitmq-broker
  version: 0+dev.27
- name: cf-rabbitmq-test
  version: 0.1.7+dev.1
- name: routing
  version: 0.143.0
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: '3263.17'
update:
  canaries: 1
  canary_watch_time: 30000-180000
  max_in_flight: 4
  serial: false
  update_watch_time: 30000-180000
