---
name: ((deployment-name))
director_uuid: ((director-uuid))

releases:
- name: cf-rabbitmq-multitenant-broker
  version: latest
- name: cf-rabbitmq-test
  version: latest
- name: routing
  version: ((cf-routing-version))
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=((cf-routing-version))
  sha1: (cf-routing-sha1))

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: ((stemcell-version))

instance_groups:
- name: rmq-broker
  instances: 1
  jobs:
  - name: rabbitmq-broker
    release: cf-rabbitmq-multitenant-broker
    properties:
      cf:
        domain: ((bosh-hostname))
      rabbitmq-broker:
        route: ((rabbitmq-broker-domain))
        cc_endpoint: http://api.((bosh-hostname))
        service:
          username: ((multitenant-rabbitmq-broker-username))
          password: ((multitenant-rabbitmq-broker-password))
          name: ((product-name))
          uuid: ((rabbitmq-broker-uuid))
          plan_uuid: ((rabbitmq-broker-plan-uuid))
        logging:
          level: debug
          print_stack_traces: false
        rabbitmq:
          hosts: ((rabbitmq-hosts))
          operator_set_policy:
            enabled: true
            policy_name: "operator_set_policy"
            policy_definition: "{\"ha-mode\":\"exactly\",\"ha-params\":2,\"ha-sync-mode\":\"automatic\"}"
            policy_priority: 50
          management_domain: ((rabbitmq-management-domain)).((bosh-hostname))
          ssl: true
          administrator:
            username: ((rabbitmq-broker-username))
            password: ((rabbitmq-broker-password))
  - name: route_registrar
    release: routing
    consumes:
      nats: {from: nats, deployment: cf}
    properties:
      route_registrar:
        routes:
        - name: ((rabbitmq-broker-domain))
          port: 4567
          registration_interval: 20s
          uris:
          - ((rabbitmq-broker-domain)).((bosh-hostname))
  vm_type: m3.medium
  stemcell: trusty
  azs:
  - eu-west-1a
  networks:
  - name: services

- name: broker-registrar
  jobs:
  - name: broker-registrar
    release: cf-rabbitmq-multitenant-broker
    properties:
      cf:
        api_url: https://api.((bosh-hostname))
        admin_username: ((cf-admin-username))
        admin_password: ((cf-admin-password))
      broker:
        service:
          name: ((product-name))
        name: ((product-name))
        protocol: ((rabbitmq-broker-protocol))
        host: ((rabbitmq-broker-domain)).((bosh-hostname))
        username: ((multitenant-rabbitmq-broker-username))
        password: ((multitenant-rabbitmq-broker-password))
  instances: 1
  lifecycle: errand
  vm_type: t2.micro
  stemcell: trusty
  azs:
  - eu-west-1a
  networks:
  - name: services

- name: broker-deregistrar
  jobs:
  - name: broker-deregistrar
    release: cf-rabbitmq-multitenant-broker
    properties:
      cf:
        api_url: https://api.((bosh-hostname))
        admin_username: ((cf-admin-username))
        admin_password: ((cf-admin-password))
      broker:
        name: ((product-name))
        service:
          name: ((product-name))
  instances: 1
  lifecycle: errand
  vm_type: t2.micro
  stemcell: trusty
  azs:
  - eu-west-1a
  networks:
  - name: services

- name: smoke-tests
  jobs:
  - name: smoke-tests
    release: cf-rabbitmq-multitenant-broker
    properties:
      cf:
        api_url: https://api.((bosh-hostname))
        domain: ((bosh-hostname))
        admin_username: ((cf-admin-username))
        admin_password: ((cf-admin-password))
      broker:
        name: ((product-name))
  instances: 1
  lifecycle: errand
  vm_type: m3.medium
  stemcell: trusty
  azs:
  - eu-west-1a
  networks:
  - name: services

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 4
  serial: false
