bosh-hostname:
cf-admin-password:
cf-admin-username:
cf-rabbitmq-broker-release-name:
deployment-name:
director-uuid:
multitenant-rabbitmq-broker-password:
multitenant-rabbitmq-broker-username:
nats-ip-address:
product-name:
rabbitmq-broker-domain:
rabbitmq-broker-password:
rabbitmq-broker-plan-uuid:
rabbitmq-broker-protocol:
rabbitmq-broker-username:
rabbitmq-broker-uuid:
rabbitmq-management-domain:
stemcell-version:
