---
name: ((deployment-name))
director_uuid: ((director-uuid))

releases:
- name: ((cf-rabbitmq-broker-release-name))
  version: latest
- name: cf-rabbitmq-test
  version: latest
- name: routing
  version: 0.143.0

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: ((stemcell-version))

instance_groups:
- name: rmq-broker
  instances: 1
  jobs:
  - name: rabbitmq-broker
    release: ((cf-rabbitmq-broker-release-name))
  - name: route_registrar
    release: routing
    properties:
      nats:
        machines: ((nats-ip-addresses))
        port: 4222
        user: nats
        password: ((nats-password))
      route_registrar:
        routes:
        - name: ((rabbitmq-broker-domain))
          port: 4567
          registration_interval: 20s
          uris:
          - ((rabbitmq-broker-domain)).((bosh-hostname))
  - name: syslog-configuration-test
    release: cf-rabbitmq-test
    properties:
      syslog-configuration-test:
        watched-log-files:
        - "/var/vcap/sys/log/rabbitmq-broker/startup_stdout.log"
        - "/var/vcap/sys/log/rabbitmq-broker/startup_stderr.log"
        - "/var/vcap/sys/log/route_registrar/route_registrar.log"
        - "/var/vcap/sys/log/route_registrar/route_registrar.err.log"
  - name: permissions-test
    release: cf-rabbitmq-test
    properties:
      permissions-test:
        directories:
        - "/var/vcap/jobs/rabbitmq-broker"
        - "/var/vcap/sys/log"
  vm_type: m3.medium
  stemcell: trusty
  azs:
  - eu-west-1a
  networks:
  - name: services

- name: broker-registrar
  jobs:
  - name: broker-registrar
    release: ((cf-rabbitmq-broker-release-name))
  instances: 1
  lifecycle: errand
  vm_type: t2.micro
  stemcell: trusty
  azs:
  - eu-west-1a
  networks:
  - name: services

- name: broker-deregistrar
  jobs:
  - name: broker-deregistrar
    release: ((cf-rabbitmq-broker-release-name))
  instances: 1
  lifecycle: errand
  vm_type: t2.micro
  stemcell: trusty
  azs:
  - eu-west-1a
  networks:
  - name: services

- name: smoke-tests
  jobs:
  - name: smoke-tests
    release: ((cf-rabbitmq-broker-release-name))
    properties:
      cf: &cf
        api_url: https://api.((bosh-hostname))
        admin_username: ((cf-admin-username))
        admin_password: ((cf-admin-password))
        org: smoke-test-org
        space: smoke-test-space
        service_offering_name: ((product-name))
  instances: 1
  lifecycle: errand
  vm_type: m3.medium
  stemcell: trusty
  azs:
  - eu-west-1a
  networks:
  - name: services

properties:
  # for broker and route registrars
  cf:
    admin_username: ((cf-admin-username))
    admin_password: ((cf-admin-password))
    api_url: http://api.((bosh-hostname))
    domain: ((bosh-hostname))
  broker:
    host: ((rabbitmq-broker-domain)).((bosh-hostname))
    protocol: ((rabbitmq-broker-protocol))
    name: ((product-name))
    username: ((multitenant-rabbitmq-broker-username))
    password: ((multitenant-rabbitmq-broker-password))
    service:
      name: ((product-name))
  syslog_aggregator:
    address: ((syslog-aggregator-address))
    port: ((syslog-aggregator-port))
  rabbitmq-broker:
    route: ((rabbitmq-broker-domain))
    cc_endpoint: http://api.((bosh-hostname))
    service:
      username: ((multitenant-rabbitmq-broker-username))
      password: ((multitenant-rabbitmq-broker-password))
      name: ((product-name))
      uuid: ((rabbitmq-broker-uuid))
      plan_uuid: ((rabbitmq-broker-plan-uuid))
    logging:
      level: debug
      print_stack_traces: false
    rabbitmq:
      hosts: ((rabbitmq-hosts))
      operator_set_policy:
        enabled: true
        policy_name: "operator_set_policy"
        policy_definition: "{\"ha-mode\":\"exactly\",\"ha-params\":2,\"ha-sync-mode\":\"automatic\"}"
        policy_priority: 50
      management_domain: ((rabbitmq-management-domain)).((bosh-hostname))
      ssl: true
      administrator:
        username: ((rabbitmq-broker-username))
        password: ((rabbitmq-broker-password))

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 4
  serial: false
