---
- type: replace
  path: /instance_groups/name=rabbitmq-server/jobs/name=rabbitmq-server/properties?/rabbitmq-server/management_tls?
  value:
    enabled: true
    key: "((tls_certificate.private_key))"
    cert: "((tls_certificate.certificate))"
    cacert: "((/services/tls_ca.certificate))"

- type: replace
  path: /variables?/-
  value:
    name: tls_certificate
    type: certificate
    options:
      ca: "/services/tls_ca"
      common_name: ((tls.common_name))
      alternative_names: ((tls.alternative_names))

