deployment-name: cf-rabbitmq-multitenant-broker

stemcell-version: 3363.29

bosh-hostname: bosh-lite.com

multitenant-rabbitmq-broker-password: broker
multitenant-rabbitmq-broker-username: broker

product-name: p-rabbitmq

rabbitmq-management-password: admin
rabbitmq-management-username: admin
rabbitmq-broker-domain: rabbitmq-multitenant-broker
rabbitmq-broker-password: broker
rabbitmq-broker-plan-uuid: 22F0B28C-B886-4123-B01B-95E54D3DE6DA
rabbitmq-broker-protocol: http
rabbitmq-broker-username: broker
rabbitmq-broker-uuid: 568725FD-AD46-44CA-9853-621416E983A4
rabbitmq-management-domain: pivotal-rabbitmq
rabbitmq-hosts: USING BOSH LINKS

syslog-port: 8081
syslog-host: 10.244.16.126

cf-admin-password: admin
cf-admin-username: admin

cluster-partition-handling-strategy: autoheal

haproxy-instances: 1
haproxy-stats-password: admin
haproxy-stats-username: admin
